# Generated by Django 2.2.1 on 2019-07-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotosrestaurante',
            old_name='id_restaurante',
            new_name='restaurante',
        ),
    ]
