# Generated by Django 2.2.1 on 2019-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_admin_restaurante',
            field=models.BooleanField(default=False),
        ),
    ]
