# Generated by Django 2.2.1 on 2019-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190803_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='calificacion_prom',
            field=models.FloatField(default=0.0),
        ),
    ]
